# SPRING CONFIGURATION
spring:
  main:
    banner-mode: "off"
    
  # DATABASE CONFIGURATION  
  datasource:
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/jumia?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    
# LOG CONFIGURATION
logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
